buildscript {
    repositories {
        google()
        //mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        flatDir {
            dirs 'libs'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
        classpath 'com.google.gms:google-services:4.4.1'

        // Add the Crashlytics Gradle plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'
    }
}


allprojects {

    version = '1.0'

    ext {

        appVersionCode = 2101113
        appVersionName = "1.14.0.11"


        gdxVersion = "1.9.14"
        // NOTE: This is for ext we need to build ffmpeg
        exoVersionCustomExt = '2.18.0'
        // NOTE: using regular exoplayer for core stuff
        exoVersion = '2.18.1'
        ijkVersionDev = '0.8.8-SNAPSHOT'
        androidBuildToolsVersion = "34.0.0"
        androidMinSdkVersion = 21
        androidCompileSdkVersion = 34
        androidTargetSdkVersion = 34
        // tell every project where to find the local project maven files
        mavenInProject = file('../mavenlocal').absoluteFile.toURI()
        defJavaVesionNum = 17
        defJavaVesionConst = JavaVersion.VERSION_17
    }

    repositories {
        maven { url mavenInProject }
        google()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
        flatDir {
            dirs '../libs'
        }
    }
}

